import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import {parseHTML} from 'linkedom';import YAML from 'yaml';
const html=async p=>parseHTML(await readFile(p,'utf8')).document;
const articleFolder=process.env.INAZ_ARTICLES_DIR||'content/articles';
async function publishedArticles(){const articles=[];for(const file of (await readdir(articleFolder)).filter(name=>name.endsWith('.md'))){const raw=await readFile(path.join(articleFolder,file),'utf8');const match=raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);assert.ok(match,`${file}: frontmatter yoxdur`);const article=YAML.parse(match[1]);if(article.status==='published')articles.push({...article,slug:file.slice(0,-3)})}return articles}
test('əsas səhifənin strukturu və brendi',async()=>{const d=await html('dist/index.html');assert.equal(d.documentElement.lang,'az');assert.match(d.title,/I’NAZ/);assert.ok(d.querySelector('main h1'));assert.ok(d.querySelector('nav'));assert.ok(d.querySelector('footer'));assert.ok(d.querySelector('link[rel=canonical]'))});
test('bütün yaradılmış HTML səhifələrində əsas elementlər var',async()=>{async function walk(dir){let out=[];for(const x of await readdir(dir,{withFileTypes:true})){const p=`${dir}/${x.name}`;out.push(...(x.isDirectory()?await walk(p):x.name.endsWith('.html')?[p]:[]))}return out}for(const p of await walk('dist')){const d=await html(p);assert.ok(d.querySelector('title'),p);assert.ok(d.querySelector('meta[name=description]'),p);assert.ok(d.querySelector('main'),p);assert.ok(d.querySelector('a.skip'),p)}});
test('axtarış indeksi və sitemap yalnız yayımlanmış məqalələri göstərir',async()=>{const expected=await publishedArticles();const index=JSON.parse(await readFile('dist/search-index.json','utf8'));assert.deepEqual(index.map(x=>x.url).sort(),expected.map(x=>`/mezmunlar/${x.slug}/`).sort());const sitemap=await readFile('dist/sitemap.xml','utf8');for(const article of expected)assert.ok(sitemap.includes(`/mezmunlar/${article.slug}/`));assert.doesNotMatch(sitemap,/\/jurnal\//)});
test('ana səhifə məqalə sayı dəyişəndə və sıfır olanda işləyir',async()=>{const expected=await publishedArticles();const d=await html('dist/index.html');assert.equal(d.querySelectorAll('.home-main-grid .lead-story').length,Math.min(2,expected.filter(a=>a.archive!==true&&a.home_section==='main').length));assert.equal(d.querySelectorAll('.home-small-grid .card').length,Math.min(4,expected.filter(a=>a.archive!==true&&a.home_section==='small').length));if(!expected.length)assert.match(d.querySelector('main')?.textContent||'',/Hələ məqalə yoxdur/);assert.equal(d.querySelectorAll('.navigation a').length,8);assert.equal(d.querySelectorAll('.footer-links a[href^="/"]').length,8);assert.doesNotMatch(d.body.textContent,/Sayt təqdimatı|Nümunə məzmun|Azərbaycanın redaksiya və lifestyle jurnalı/);assert.match(d.body.textContent,/Dəb, həyat tərzi və mədəniyyət jurnalı/);assert.equal(d.querySelector('.masthead')?.textContent.includes('AZ'),false)});
test('CMS və yerləşdirmə faylları mövcuddur',async()=>{for(const p of ['.pages.yml','.github/workflows/deploy.yml','dist/robots.txt','dist/sitemap.xml','README.md'])assert.ok((await readFile(p,'utf8')).length>20,p)});
test('SEO ünvanları əsas domeni göstərir',async()=>{const d=await html('dist/index.html');assert.equal(d.querySelector('link[rel=canonical]')?.getAttribute('href'),'https://inazmagazine.com/');assert.equal(d.querySelector('meta[property="og:url"]')?.getAttribute('content'),'https://inazmagazine.com/');const sitemap=await readFile('dist/sitemap.xml','utf8');assert.match(sitemap,/<loc>https:\/\/inazmagazine\.com\//);assert.doesNotMatch(sitemap,/github\.io/);const robots=await readFile('dist/robots.txt','utf8');assert.match(robots,/Sitemap: https:\/\/inazmagazine\.com\/sitemap\.xml/);assert.equal((await readFile('dist/CNAME','utf8')).trim(),'inazmagazine.com')});
