import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import YAML from 'yaml';
import MarkdownIt from 'markdown-it';
import sanitizeHtml from 'sanitize-html';
import sharp from 'sharp';
import {createTheme,themeCss,FONT_CHOICES,contrastText} from './theme.mjs';

const md = new MarkdownIt({ html: false, linkify: true, typographer: true });
const root = process.cwd();
const out = path.join(root, 'dist');
const basePath = (process.env.BASE_PATH || '').replace(/\/$/, '');
const readYaml = async file => YAML.parse(await readFile(path.join(root, file), 'utf8'));
const readMarkdownBody = async file => { const raw=await readFile(path.join(root,file),'utf8'); const match=raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/); return (match?match[1]:raw).trim(); };
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const slug = value => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ə/gi,'e').replace(/ı/g,'i').replace(/İ/g,'i').replace(/ş/gi,'s').replace(/ç/gi,'c').replace(/ğ/gi,'g').replace(/ö/gi,'o').replace(/ü/gi,'u').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const fmtDate = date => new Intl.DateTimeFormat('az-AZ', { day:'numeric', month:'long', year:'numeric' }).format(new Date(`${date}T12:00:00`));
const renderMd = body => sanitizeHtml(md.render(body || ''), { allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img','figure','figcaption']), allowedAttributes:{a:['href','title','target','rel'],img:['src','alt','title','loading','width','height']}, allowedSchemes:['http','https','mailto','tel'] });

async function collection(dir) {
  const folder = dir === 'articles' && process.env.INAZ_ARTICLES_DIR ? process.env.INAZ_ARTICLES_DIR : path.join(root,'content',dir);
  const files = (await readdir(folder)).filter(file=>file.endsWith('.md'));
  return Promise.all(files.map(async file=>{const raw=await readFile(path.join(folder,file),'utf8');const match=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);if(!match)throw new Error(`Frontmatter yoxdur: ${file}`);return {...YAML.parse(match[1]),body:match[2],slug:file.replace(/\.md$/,'')};}));
}

const site=await readYaml('content/data/site.yml');
// An optional design file must never break publishing when removed or malformed.
let design={};
try { design=YAML.parse(await readFile(process.env.INAZ_DESIGN_FILE||'content/data/design.yml','utf8'))||{}; }
catch(error) { if(error.code!=='ENOENT')console.warn('Dizayn ayarları oxunmadı; default palitra istifadə olunur.'); }
const theme=createTheme(design);
const styleSource=themeCss(theme)+await readFile('src/styles.css','utf8');
const siteOrigin=process.env.SITE_URL||site.base_url;
const nav=(await readYaml('content/data/navigation.yml')).filter(x=>x.active).sort((a,b)=>a.order-b.order);
const categories=(await readYaml('content/data/categories.yml')).filter(x=>x.active).sort((a,b)=>a.order-b.order);
const home=await readYaml('content/data/home.yml');
const articles=(await collection('articles')).filter(x=>x.status==='published').sort((a,b)=>new Date(b.date)-new Date(a.date));
const pages=await collection('pages');
const aboutText=await readMarkdownBody('haqqinda.md');
const missionText=await readMarkdownBody('cumle.md');

await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp('public',out,{recursive:true});await writeFile(path.join(out,'styles.css'),styleSource);
// Generate square variants from the supplied logo, preserving its proportions.
for(const size of [16,32,48,96,180]) await sharp(path.join(root,'favicon.png')).resize(size,size,{fit:'contain',background:'#ffffff'}).png().toFile(path.join(out,size===180?'apple-touch-icon.png':`favicon-${size}.png`));
await cp(path.join(out,'favicon-96.png'),path.join(out,'favicon.png'));
const clientSource=(await readFile('src/client.js','utf8')).replace("fetch('/search-index.json')",`fetch('${basePath}/search-index.json')`);await writeFile(path.join(out,'client.js'),clientSource);
await mkdir(path.join(out,'fonts'),{recursive:true});
for(const name of new Set(Object.values(theme.fonts)))for(const file of FONT_CHOICES[name].files)await cp(path.join('assets/fonts',file),path.join(out,'fonts',file));
// Logos live in public/media so Pages CMS can preview and replace them.
const localMedia = src => typeof src === 'string' && src.startsWith('/media/') && !src.includes('..') && existsSync(path.join(root,'public',src.slice(1)));
for (const [file,original] of [['logo-light.png','logowhite.PNG'],['logo-dark.png','logoblack.PNG']]) {
  const target=path.join(out,'media',file);
  if (!existsSync(target)) await sharp(path.join(root,original)).trim({background:{r:0,g:0,b:0,alpha:0}}).resize({width:520}).png().toFile(target);
}
if (!existsSync(path.join(out,'media','placeholder.svg'))) await writeFile(path.join(out,'media','placeholder.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900"><rect width="1200" height="900" fill="#d9b99b"/></svg>');
const mediaUrl = src => localMedia(src) || /^https:\/\//.test(src || '') ? src : '/media/placeholder.svg';
if (!site.logo_light?.startsWith('/media/') || !existsSync(path.join(out,site.logo_light.slice(1)))) site.logo_light='/media/logo-light.png';

const optimized=new Map();await mkdir(path.join(out,'media','optimized'),{recursive:true});
for(const src of [...new Set(articles.flatMap(a=>[a.image,...(a.gallery||[]).map(g=>g.image)]).filter(Boolean))]){const input=path.join(root,'public',src.replace(/^\//,''));try{const meta=await sharp(input).metadata();const key=createHash('sha256').update(src).digest('hex').slice(0,16);const variants=[];for(const width of [480,900,1400]){if(meta.width&&width>meta.width&&variants.length)continue;await sharp(input).resize({width,withoutEnlargement:true}).webp({quality:80,effort:5}).toFile(path.join(out,'media','optimized',`${key}-${width}.webp`));variants.push({width:Math.min(width,meta.width||width),url:`/media/optimized/${key}-${width}.webp`});}optimized.set(src,{variants,width:meta.width||1400,height:meta.height||1000});}catch(error){console.warn(`Şəkil optimallaşdırılmadı: ${src}: ${error.message}`)}}
const image=(src,alt='',eager=false,cls='',sizes='(max-width:720px) 100vw, 50vw')=>{src=mediaUrl(src);const data=optimized.get(src);const attrs=`${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async"`;if(!data)return`<picture><img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" ${attrs} width="1200" height="900"></picture>`;return`<picture><source type="image/webp" srcset="${data.variants.map(x=>`${x.url} ${x.width}w`).join(', ')}" sizes="${sizes}"><img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" ${attrs} width="${data.width}" height="${data.height}"></picture>`};
const card=(a,compact=false)=>`<a class="card ${compact?'card-compact':''}" href="/mezmunlar/${a.slug}/">${image(a.image,a.image_alt,false,'',compact?'(max-width:720px) 50vw, 25vw':'(max-width:720px) 100vw, 33vw')}<span class="card-category">${esc(a.category)}</span><h3>${esc(a.title)}</h3>${compact?'':`<p>${esc(a.description)}</p>`}<time datetime="${a.date}">${fmtDate(a.date)}</time></a>`;
const brand=(isFooter=false)=>`<a class="brand" href="/" aria-label="I’NAZ ana səhifə"><img src="${contrastText(theme.colors[isFooter?'footer':'header'])==='#ffffff'?site.logo_light:site.logo_dark}" alt="I’NAZ — ${esc(site.credit)}" width="520" height="180"></a>`;
const header=current=>`<a class="skip" href="#main">Əsas məzmuna keç</a><header class="site-header"><div class="wrap masthead"><span class="masthead-note">Dəb, həyat tərzi və mədəniyyət jurnalı</span>${brand()}<a class="header-search" href="/axtaris/" aria-label="Saytda axtarış">Axtarış</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menyu</button></div><nav class="navigation wrap" id="main-nav" aria-label="Əsas naviqasiya">${nav.map(n=>`<a href="${n.url}" ${current===n.url?'aria-current="page"':''}>${esc(n.label)}</a>`).join('')}</nav></header>`;
const footer=()=>`<footer class="site-footer"><div class="wrap footer-main"><div class="footer-brand">${brand(true)}</div><div><h2 class="footer-heading">Bölmələr</h2><nav class="footer-links">${nav.map(n=>`<a href="${n.url}">${esc(n.label)}</a>`).join('')}</nav></div><div><h2 class="footer-heading">Əlaqə</h2><div class="footer-links"><a href="mailto:${site.email}">${site.email}</a><a href="tel:${site.phone.replace(/\s/g,'')}">${site.phone}</a><a href="${site.instagram}" target="_blank" rel="noopener noreferrer">Instagram</a><a href="${site.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} I’NAZ. Bütün hüquqlar qorunur.</span><nav><a href="/mexfilik/">Məxfilik siyasəti</a><a href="/istifade-qaydalari/">İstifadə qaydaları</a></nav></div></footer>`;
const assetVersion=createHash('sha256').update(styleSource).update(clientSource).digest('hex').slice(0,12);
const doc=({title,description,body,current='',extra='',canonical='/'})=>`<!doctype html><html lang="az"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.base_url}${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.base_url}${canonical}"><meta name="theme-color" content="${theme.colors.background}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"><link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png"><link rel="icon" type="image/png" sizes="96x96" href="/favicon.png"><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"><link rel="stylesheet" href="/styles.css?v=${assetVersion}">${extra}</head><body>${header(current)}<main id="main">${body}</main>${footer()}<script src="/client.js?v=${assetVersion}" defer></script></body></html>`;
const prefixHtml=html=>{let result=html.replaceAll(site.base_url,`${siteOrigin}${basePath}`);if(basePath)result=result.replace(/\b(href|src|srcset)="\/(?!\/)/g,`$1="${basePath}/`).replace(/, \/media\//g,`, ${basePath}/media/`);return result};
async function writeRoute(route,html){const folder=path.join(out,route);await mkdir(folder,{recursive:true});await writeFile(path.join(folder,'index.html'),prefixHtml(html));}

const ordered=[...articles].filter(a=>a.home_section&&a.home_section!=='hidden').sort((a,b)=>(a.home_order??99)-(b.home_order??99));const selectedMain=ordered.filter(a=>a.home_section==='main').slice(0,2);const mainStories=selectedMain;const selectedSmall=ordered.filter(a=>a.home_section==='small').slice(0,4);const smallStories=selectedSmall;
const homeHtml=`<section class="home-lead wrap">${articles.length?`<div class="home-main-grid">${mainStories.map((a,i)=>`<a class="lead-story" href="/mezmunlar/${a.slug}/">${image(a.image,a.image_alt,true,'lead-image','(max-width:720px) 100vw, 50vw')}<span class="card-category">${esc(a.category)}</span><${i?'h2':'h1'} class="lead-title">${esc(a.title)}</${i?'h2':'h1'}><p>${esc(a.description)}</p></a>`).join('')}</div><div class="home-small-grid">${smallStories.map(a=>card(a,true)).join('')}</div>`:'<div class="empty"><h1>Hələ məqalə yoxdur</h1><p>Yeni məzmunlar hazırlanır.</p></div>'}</section><section class="mission wrap"><span class="eyebrow">I’NAZ haqqında</span><h2>${esc(home.mission_title)}</h2><p>${esc(missionText)}</p><a class="text-link" href="/haqqimizda/">Daha ətraflı <span>→</span></a></section>`;
await writeRoute('',doc({title:`${site.name} Magazine`,description:site.description,body:homeHtml,canonical:'/'}));

function listing(title,desc,list,filters=false){return`<header class="page-heading wrap"><span class="eyebrow">I’NAZ Magazine</span><h1>${esc(title)}</h1><p>${esc(desc)}</p></header>${filters?`<section class="catalog-controls"><div class="wrap"><form class="search-line" action="/mezmunlar/" method="get"><label class="field">Məzmunlarda axtar<input name="q" type="search" autocomplete="off" placeholder="Başlıq, müəllif və ya söz..."></label><label class="field sort-field">Sıralama<select name="sort"><option value="new">Ən yeni</option><option value="old">Ən köhnə</option></select></label></form><nav class="filters" aria-label="Kateqoriyalar"><a href="/mezmunlar/" aria-current="true">Hamısı</a>${categories.map(c=>`<a href="/${c.slug}/">${esc(c.name)}</a>`).join('')}</nav></div></section>`:''}<section class="listing wrap"><div class="results-meta"><span data-count>${list.length} məzmun</span></div><div class="grid" data-listing>${list.map(a=>`<div data-search="${esc(`${a.title} ${a.description} ${a.author} ${a.body}`.toLocaleLowerCase('az'))}" data-category="${slug(a.category)}" data-date="${a.date}">${card(a)}</div>`).join('')}</div><div class="empty" data-empty ${list.length?'hidden':''}><h2>${list.length?'Nəticə tapılmadı':'Hələ məqalə yoxdur'}</h2><p>${list.length?'Axtarış sözünü dəyişin.':'Yeni məzmunlar hazırlanır.'}</p></div></section>`}
await writeRoute('mezmunlar',doc({title:`Məzmunlar — ${site.name}`,description:'I’NAZ jurnalının bütün məzmunları.',body:listing('Məzmunlar','Dəb, həyat tərzi, peşəkarlar, brendlər və mədəniyyət haqqında bütün yazılar.',articles,true),current:'/mezmunlar/',canonical:'/mezmunlar/'}));
for(const category of categories){const list=articles.filter(a=>a.category===category.name);await writeRoute(category.slug,doc({title:`${category.name} — ${site.name}`,description:category.description,body:listing(category.name,category.description,list),current:`/${category.slug}/`,canonical:`/${category.slug}/`}));}

for(const a of articles){const bg=a.background||'#F7EBDD';const h=bg.replace('#','');const [r,g,b]=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255);const ink=a.text_color==='white'?'#fff':a.text_color==='black'?'#24130b':(.2126*r+.7152*g+.0722*b)>.55?'#24130b':'#fff';const json=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:a.title,datePublished:a.date,author:{'@type':'Organization',name:a.author},publisher:{'@type':'Organization',name:'I’NAZ'},image:`${site.base_url}${a.image}`,description:a.description}).replace(/</g,'\\u003c');const gallery=a.gallery?.length?`<div class="gallery">${a.gallery.map(x=>`<figure>${image(x.image,x.alt)}${x.caption?`<figcaption>${esc(x.caption)}</figcaption>`:''}</figure>`).join('')}</div>`:'';const body=`<article class="article-shell" style="--article-bg:${bg};--article-ink:${ink}"><header class="article-header"><span class="eyebrow">${esc(a.category)}</span><h1>${esc(a.title)}</h1><p class="article-deck">${esc(a.description)}</p><div class="byline"><span>${esc(a.author)}</span><time datetime="${a.date}">${fmtDate(a.date)}</time></div>${a.partner?'<span class="label">Tərəfdaş materialı</span>':''}</header><figure class="article-cover wrap">${image(a.image,a.image_alt,true,'','100vw')}${a.photo_credit?`<figcaption>Foto: ${esc(a.photo_credit)}</figcaption>`:''}</figure><div class="article-body prose">${renderMd(a.body)}${gallery}<div class="share"><strong>Paylaş</strong><a href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(site.base_url+`/mezmunlar/${a.slug}/`)}" target="_blank" rel="noopener noreferrer">Facebook</a><button type="button" data-copy-link>Keçidi köçür</button></div></div></article><section class="related section wrap"><div class="section-top"><h2>Oxşar məzmunlar</h2></div><div class="grid">${articles.filter(x=>x.slug!==a.slug).slice(0,3).map(x=>card(x,true)).join('')}</div></section>`;await writeRoute(`mezmunlar/${a.slug}`,doc({title:a.seo?.seo_title||a.seo_title||`${a.title} — ${site.name}`,description:a.seo?.seo_description||a.seo_description||a.description,body,current:'/mezmunlar/',canonical:`/mezmunlar/${a.slug}/`,extra:`<script type="application/ld+json">${json}</script>`}));}

const about=pages.find(p=>p.slug==='about');const aboutBody=`<section class="section wrap static-layout"><header><span class="eyebrow">I’NAZ Magazine</span><h1>${about.title}</h1></header><div class="prose">${renderMd(aboutText)}<div class="contact-block"><h2>Əlaqə və əməkdaşlıq</h2><p>Redaksiya, reklam və əməkdaşlıq müraciətləri üçün:</p><p><a href="mailto:${site.email}">${site.email}</a><br><a href="tel:${site.phone.replace(/\s/g,'')}">${site.phone}</a><br><a href="${site.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp ilə yazın</a><br><a href="${site.instagram}" target="_blank" rel="noopener noreferrer">Instagram</a></p></div></div></section>`;await writeRoute('haqqimizda',doc({title:`Haqqımızda — ${site.name}`,description:about.description,body:aboutBody,current:'/haqqimizda/',canonical:'/haqqimizda/'}));
for(const [route,pageSlug] of [['mexfilik','privacy'],['istifade-qaydalari','terms']]){const page=pages.find(p=>p.slug===pageSlug);await writeRoute(route,doc({title:`${page.title} — ${site.name}`,description:page.description,body:`<section class="section wrap static-layout"><header><h1>${page.title}</h1></header><div class="prose">${renderMd(page.body)}</div></section>`,canonical:`/${route}/`}));}
const searchBody=`<header class="page-heading wrap"><h1>Axtarış</h1><p>I’NAZ məzmunlarında başlıq, müəllif və mətn üzrə axtarın.</p></header><section class="listing wrap"><label class="field"><span class="eyebrow">Axtarış sözü</span><input type="search" data-global-search autocomplete="off" placeholder="Məsələn: yaradıcılıq"></label><p class="status" data-search-status aria-live="polite">Axtarmaq üçün ən azı iki hərf yazın.</p><div class="grid" data-search-results></div></section>`;await writeRoute('axtaris',doc({title:`Axtarış — ${site.name}`,description:'I’NAZ saytında axtarış.',body:searchBody,current:'/axtaris/',canonical:'/axtaris/'}));
await writeFile(path.join(out,'search-index.json'),JSON.stringify(articles.map(a=>({title:a.title,description:a.description,author:a.author,date:a.date,url:`${basePath}/mezmunlar/${a.slug}/`,image:`${basePath}${optimized.get(a.image)?.variants[0]?.url||mediaUrl(a.image)}`,alt:a.image_alt,text:a.body.replace(/[#>*_`]/g,' ')}))));
await writeFile(path.join(out,'404.html'),prefixHtml(doc({title:`Səhifə tapılmadı — ${site.name}`,description:'Axtardığınız səhifə tapılmadı.',body:'<section class="error-page"><h1>404</h1><h2>Səhifə tapılmadı</h2><p>Axtardığınız ünvan dəyişmiş və ya silinmiş ola bilər.</p><a class="button" href="/">Ana səhifəyə qayıt</a></section>'})));
const urls=['/','/mezmunlar/',...categories.map(c=>`/${c.slug}/`),'/haqqimizda/','/axtaris/','/mexfilik/','/istifade-qaydalari/',...articles.map(a=>`/mezmunlar/${a.slug}/`)];await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${siteOrigin}${basePath}${u}</loc></url>`).join('')}</urlset>`);await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: ${basePath||'/'}\nSitemap: ${siteOrigin}${basePath}/sitemap.xml\n`);await writeFile(path.join(out,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n');
console.log(`I’NAZ build tamamlandı: ${articles.length} məqalə, ${urls.length} URL`);
