import { createServer } from 'node:http';import { readFile,stat } from 'node:fs/promises';import { watch } from 'node:fs';import path from 'node:path';import { spawn } from 'node:child_process';
const port=Number(process.env.PORT||4173);
const basePath=(process.env.BASE_PATH||'').replace(/\/$/,'');
const watching=process.argv.includes('--watch');
const build=()=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['scripts/build.mjs'],{stdio:'inherit'});p.on('exit',c=>c?reject(new Error('Build alınmadı')):resolve())});
if(watching) await build();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.xml':'application/xml; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.svg':'image/svg+xml','.avif':'image/avif','.jpeg':'image/jpeg'};
const server=createServer(async(req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(basePath){if(!pathname.startsWith(basePath+'/'))throw new Error('Outside base path');pathname=pathname.slice(basePath.length);}let rel=pathname.replace(/^\/+/, '');if(rel.split(/[\\/]/).includes('..'))throw new Error('Invalid path');let file=path.join(process.cwd(),'dist',rel);try{if((await stat(file)).isDirectory())file=path.join(file,'index.html')}catch{if(!path.extname(file))file=path.join(file,'index.html')}const data=await readFile(file);res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(data)}catch{try{res.writeHead(404,{'content-type':'text/html; charset=utf-8'});res.end(await readFile('dist/404.html'))}catch{res.end('404')}}});server.listen(port,'127.0.0.1',()=>console.log(`Local: http://127.0.0.1:${port}${basePath}/`));
if(watching){let timer,running=false,pending=false;const rebuild=async()=>{if(running){pending=true;return}running=true;try{await build();console.log('Dəyişikliklər yenidən quruldu.')}catch(e){console.error(e.message)}finally{running=false;if(pending){pending=false;rebuild()}}};for(const dir of ['content','src','public'])watch(dir,{recursive:true},()=>{clearTimeout(timer);timer=setTimeout(rebuild,250)});for(const file of ['haqqinda.md','cumle.md','scripts/build.mjs'])watch(file,()=>{clearTimeout(timer);timer=setTimeout(rebuild,250)})}
